// Mock data for frontend development before API is ready

export const mockEmployees = [
  {
    EmployeeID: 1,
    FullName: "Nguyen Van An",
    DateOfBirth: "1990-05-15",
    Gender: "Male",
    PhoneNumber: "0901234567",
    Email: "an.nguyen@company.com",
    HireDate: "2019-03-01",
    Status: "Active",
    DepartmentID: 1,
    PositionID: 1,
    DepartmentName: "Engineering",
    PositionName: "Software Engineer",
  },
  {
    EmployeeID: 2,
    FullName: "Tran Thi Binh",
    DateOfBirth: "1992-08-20",
    Gender: "Female",
    PhoneNumber: "0907654321",
    Email: "binh.tran@company.com",
    HireDate: "2020-06-15",
    Status: "Active",
    DepartmentID: 2,
    PositionID: 3,
    DepartmentName: "Human Resources",
    PositionName: "HR Specialist",
  },
  {
    EmployeeID: 3,
    FullName: "Le Hoang Cuong",
    DateOfBirth: "1988-12-10",
    Gender: "Male",
    PhoneNumber: "0912345678",
    Email: "cuong.le@company.com",
    HireDate: "2018-01-10",
    Status: "Active",
    DepartmentID: 1,
    PositionID: 2,
    DepartmentName: "Engineering",
    PositionName: "Senior Developer",
  },
  {
    EmployeeID: 4,
    FullName: "Pham Minh Duc",
    DateOfBirth: "1995-03-25",
    Gender: "Male",
    PhoneNumber: "0923456789",
    Email: "duc.pham@company.com",
    HireDate: "2021-09-01",
    Status: "Active",
    DepartmentID: 3,
    PositionID: 5,
    DepartmentName: "Finance",
    PositionName: "Accountant",
  },
  {
    EmployeeID: 5,
    FullName: "Vo Thi Em",
    DateOfBirth: "1993-07-30",
    Gender: "Female",
    PhoneNumber: "0934567890",
    Email: "em.vo@company.com",
    HireDate: "2022-02-14",
    Status: "Active",
    DepartmentID: 4,
    PositionID: 6,
    DepartmentName: "Marketing",
    PositionName: "Marketing Executive",
  },
  {
    EmployeeID: 6,
    FullName: "Hoang Van Phuc",
    DateOfBirth: "1985-11-05",
    Gender: "Male",
    PhoneNumber: "0945678901",
    Email: "phuc.hoang@company.com",
    HireDate: "2016-04-20",
    Status: "Active",
    DepartmentID: 1,
    PositionID: 4,
    DepartmentName: "Engineering",
    PositionName: "Tech Lead",
  },
  {
    EmployeeID: 7,
    FullName: "Ngo Thi Giang",
    DateOfBirth: "1991-09-18",
    Gender: "Female",
    PhoneNumber: "0956789012",
    Email: "giang.ngo@company.com",
    HireDate: "2020-11-01",
    Status: "Inactive",
    DepartmentID: 2,
    PositionID: 7,
    DepartmentName: "Human Resources",
    PositionName: "HR Manager",
  },
  {
    EmployeeID: 8,
    FullName: "Bui Quang Huy",
    DateOfBirth: "1994-01-22",
    Gender: "Male",
    PhoneNumber: "0967890123",
    Email: "huy.bui@company.com",
    HireDate: "2023-05-10",
    Status: "Active",
    DepartmentID: 3,
    PositionID: 8,
    DepartmentName: "Finance",
    PositionName: "Financial Analyst",
  },
  {
    EmployeeID: 9,
    FullName: "Dang Thi Lan",
    DateOfBirth: "1996-04-12",
    Gender: "Female",
    PhoneNumber: "0978901234",
    Email: "lan.dang@company.com",
    HireDate: "2024-01-15",
    Status: "Active",
    DepartmentID: 4,
    PositionID: 9,
    DepartmentName: "Marketing",
    PositionName: "Content Creator",
  },
  {
    EmployeeID: 10,
    FullName: "Cao Van Khanh",
    DateOfBirth: "1987-06-08",
    Gender: "Male",
    PhoneNumber: "0989012345",
    Email: "khanh.cao@company.com",
    HireDate: "2017-08-01",
    Status: "Active",
    DepartmentID: 5,
    PositionID: 10,
    DepartmentName: "Operations",
    PositionName: "Operations Manager",
  },
];

export const mockDepartments = [
  {
    DepartmentID: 1,
    DepartmentName: "Engineering",
    Description: "Software development and IT infrastructure",
    EmployeeCount: 3,
  },
  {
    DepartmentID: 2,
    DepartmentName: "Human Resources",
    Description: "HR management and recruitment",
    EmployeeCount: 2,
  },
  {
    DepartmentID: 3,
    DepartmentName: "Finance",
    Description: "Financial planning and accounting",
    EmployeeCount: 2,
  },
  {
    DepartmentID: 4,
    DepartmentName: "Marketing",
    Description: "Marketing and brand management",
    EmployeeCount: 2,
  },
  {
    DepartmentID: 5,
    DepartmentName: "Operations",
    Description: "Business operations and logistics",
    EmployeeCount: 1,
  },
];

export const mockPositions = [
  {
    PositionID: 1,
    PositionName: "Software Engineer",
    Description: "Develops software applications",
  },
  {
    PositionID: 2,
    PositionName: "Senior Developer",
    Description: "Senior software developer",
  },
  {
    PositionID: 3,
    PositionName: "HR Specialist",
    Description: "Handles HR operations",
  },
  {
    PositionID: 4,
    PositionName: "Tech Lead",
    Description: "Leads technical teams",
  },
  {
    PositionID: 5,
    PositionName: "Accountant",
    Description: "Manages financial records",
  },
  {
    PositionID: 6,
    PositionName: "Marketing Executive",
    Description: "Executes marketing campaigns",
  },
  {
    PositionID: 7,
    PositionName: "HR Manager",
    Description: "Manages HR department",
  },
  {
    PositionID: 8,
    PositionName: "Financial Analyst",
    Description: "Analyzes financial data",
  },
  {
    PositionID: 9,
    PositionName: "Content Creator",
    Description: "Creates marketing content",
  },
  {
    PositionID: 10,
    PositionName: "Operations Manager",
    Description: "Manages business operations",
  },
];

export const mockSalaries = [
  {
    SalaryID: 1,
    EmployeeID: 1,
    EmployeeName: "Nguyen Van An",
    BaseSalary: 25000000,
    Bonus: 3000000,
    Deductions: 2500000,
    NetSalary: 25500000,
    SalaryMonth: "2026-01",
  },
  {
    SalaryID: 2,
    EmployeeID: 1,
    EmployeeName: "Nguyen Van An",
    BaseSalary: 25000000,
    Bonus: 5000000,
    Deductions: 2500000,
    NetSalary: 27500000,
    SalaryMonth: "2026-02",
  },
  {
    SalaryID: 3,
    EmployeeID: 2,
    EmployeeName: "Tran Thi Binh",
    BaseSalary: 20000000,
    Bonus: 2000000,
    Deductions: 2000000,
    NetSalary: 20000000,
    SalaryMonth: "2026-01",
  },
  {
    SalaryID: 4,
    EmployeeID: 2,
    EmployeeName: "Tran Thi Binh",
    BaseSalary: 20000000,
    Bonus: 2000000,
    Deductions: 2000000,
    NetSalary: 20000000,
    SalaryMonth: "2026-02",
  },
  {
    SalaryID: 5,
    EmployeeID: 3,
    EmployeeName: "Le Hoang Cuong",
    BaseSalary: 35000000,
    Bonus: 5000000,
    Deductions: 3500000,
    NetSalary: 36500000,
    SalaryMonth: "2026-01",
  },
  {
    SalaryID: 6,
    EmployeeID: 3,
    EmployeeName: "Le Hoang Cuong",
    BaseSalary: 35000000,
    Bonus: 4000000,
    Deductions: 3500000,
    NetSalary: 35500000,
    SalaryMonth: "2026-02",
  },
  {
    SalaryID: 7,
    EmployeeID: 4,
    EmployeeName: "Pham Minh Duc",
    BaseSalary: 22000000,
    Bonus: 2000000,
    Deductions: 2200000,
    NetSalary: 21800000,
    SalaryMonth: "2026-01",
  },
  {
    SalaryID: 8,
    EmployeeID: 5,
    EmployeeName: "Vo Thi Em",
    BaseSalary: 18000000,
    Bonus: 1500000,
    Deductions: 1800000,
    NetSalary: 17700000,
    SalaryMonth: "2026-01",
  },
  {
    SalaryID: 9,
    EmployeeID: 6,
    EmployeeName: "Hoang Van Phuc",
    BaseSalary: 45000000,
    Bonus: 8000000,
    Deductions: 4500000,
    NetSalary: 48500000,
    SalaryMonth: "2026-01",
  },
  {
    SalaryID: 10,
    EmployeeID: 6,
    EmployeeName: "Hoang Van Phuc",
    BaseSalary: 45000000,
    Bonus: 7000000,
    Deductions: 4500000,
    NetSalary: 47500000,
    SalaryMonth: "2026-02",
  },
];

export const mockAttendance = [
  {
    AttendanceID: 1,
    EmployeeID: 1,
    EmployeeName: "Nguyen Van An",
    WorkDays: 22,
    LeaveDays: 1,
    AbsentDays: 0,
    Month: "2026-01",
  },
  {
    AttendanceID: 2,
    EmployeeID: 1,
    EmployeeName: "Nguyen Van An",
    WorkDays: 20,
    LeaveDays: 2,
    AbsentDays: 0,
    Month: "2026-02",
  },
  {
    AttendanceID: 3,
    EmployeeID: 2,
    EmployeeName: "Tran Thi Binh",
    WorkDays: 21,
    LeaveDays: 2,
    AbsentDays: 0,
    Month: "2026-01",
  },
  {
    AttendanceID: 4,
    EmployeeID: 3,
    EmployeeName: "Le Hoang Cuong",
    WorkDays: 23,
    LeaveDays: 0,
    AbsentDays: 0,
    Month: "2026-01",
  },
  {
    AttendanceID: 5,
    EmployeeID: 4,
    EmployeeName: "Pham Minh Duc",
    WorkDays: 18,
    LeaveDays: 3,
    AbsentDays: 2,
    Month: "2026-01",
  },
  {
    AttendanceID: 6,
    EmployeeID: 5,
    EmployeeName: "Vo Thi Em",
    WorkDays: 20,
    LeaveDays: 2,
    AbsentDays: 1,
    Month: "2026-01",
  },
  {
    AttendanceID: 7,
    EmployeeID: 6,
    EmployeeName: "Hoang Van Phuc",
    WorkDays: 22,
    LeaveDays: 1,
    AbsentDays: 0,
    Month: "2026-01",
  },
  {
    AttendanceID: 8,
    EmployeeID: 7,
    EmployeeName: "Ngo Thi Giang",
    WorkDays: 15,
    LeaveDays: 5,
    AbsentDays: 3,
    Month: "2026-01",
  },
  {
    AttendanceID: 9,
    EmployeeID: 8,
    EmployeeName: "Bui Quang Huy",
    WorkDays: 22,
    LeaveDays: 1,
    AbsentDays: 0,
    Month: "2026-01",
  },
  {
    AttendanceID: 10,
    EmployeeID: 9,
    EmployeeName: "Dang Thi Lan",
    WorkDays: 21,
    LeaveDays: 2,
    AbsentDays: 0,
    Month: "2026-01",
  },
];

export const mockDividends = [
  {
    DividendID: 1,
    EmployeeID: 1,
    EmployeeName: "Nguyen Van An",
    DividendAmount: 15000000,
    DividendDate: "2025-12-15",
  },
  {
    DividendID: 2,
    EmployeeID: 3,
    EmployeeName: "Le Hoang Cuong",
    DividendAmount: 25000000,
    DividendDate: "2025-12-15",
  },
  {
    DividendID: 3,
    EmployeeID: 6,
    EmployeeName: "Hoang Van Phuc",
    DividendAmount: 35000000,
    DividendDate: "2025-12-15",
  },
  {
    DividendID: 4,
    EmployeeID: 10,
    EmployeeName: "Cao Van Khanh",
    DividendAmount: 20000000,
    DividendDate: "2025-12-15",
  },
];

export const mockAlerts = [
  {
    id: 1,
    type: "anniversary",
    title: "Work Anniversary",
    message: "Hoang Van Phuc will celebrate 10 years on April 20, 2026",
    severity: "info",
    read: false,
    date: "2026-03-10",
  },
  {
    id: 2,
    type: "anniversary",
    title: "Work Anniversary",
    message: "Le Hoang Cuong will celebrate 8 years on January 10, 2026",
    severity: "info",
    read: true,
    date: "2026-01-05",
  },
  {
    id: 3,
    type: "leave",
    title: "Leave Limit Exceeded",
    message:
      "Ngo Thi Giang has taken 5 leave days and 3 absent days in January",
    severity: "warning",
    read: false,
    date: "2026-02-01",
  },
  {
    id: 4,
    type: "leave",
    title: "High Absence",
    message: "Pham Minh Duc had 2 absent days in January 2026",
    severity: "warning",
    read: false,
    date: "2026-02-01",
  },
  {
    id: 5,
    type: "salary",
    title: "Salary Discrepancy",
    message: "Hoang Van Phuc bonus decreased by 12.5% from Jan to Feb 2026",
    severity: "error",
    read: false,
    date: "2026-03-01",
  },
  {
    id: 6,
    type: "anniversary",
    title: "Work Anniversary",
    message: "Nguyen Van An will celebrate 7 years on March 1, 2026",
    severity: "info",
    read: true,
    date: "2026-02-25",
  },
];

export const mockDashboardStats = {
  totalEmployees: 10,
  activeEmployees: 9,
  inactiveEmployees: 1,
  totalDepartments: 5,
  totalPositions: 10,
  totalPayroll: 283500000,
  averageSalary: 28350000,
  unreadAlerts: 4,
  departmentDistribution: [
    { name: "Engineering", value: 3 },
    { name: "Human Resources", value: 2 },
    { name: "Finance", value: 2 },
    { name: "Marketing", value: 2 },
    { name: "Operations", value: 1 },
  ],
  monthlySalaryTrend: [
    { month: "Sep 2025", total: 250000000 },
    { month: "Oct 2025", total: 258000000 },
    { month: "Nov 2025", total: 262000000 },
    { month: "Dec 2025", total: 270000000 },
    { month: "Jan 2026", total: 278000000 },
    { month: "Feb 2026", total: 283500000 },
  ],
  statusDistribution: [
    { name: "Active", value: 9 },
    { name: "Inactive", value: 1 },
  ],
  genderDistribution: [
    { name: "Male", value: 6 },
    { name: "Female", value: 4 },
  ],
  attendanceSummary: {
    totalWorkDays: 204,
    totalLeaveDays: 19,
    totalAbsentDays: 6,
  },
};
